### ISSUE TITLE
Add role alias support to role assignments

### ISSUE THREAD

**Issue by drklee3** [sushiibot/sushii-2#27]
#### Current behavior

only supports the role name

```yaml
...
    roles:
      - name: test
        primary_id: 141066325777711104
```

Only matches +test or -test

#### Expected behavior

Should allow multiple matches from an additional alias field

```yaml
...
    roles:
      - name: test
        aliases: ["tst", "anotheralias"]
        primary_id: 141066325777711104
```

So this matches +/-text, tst, and anotheralias
